### ISSUE TITLE
Embed-milvus required python>3.6 instead of python>=3.6

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/embd-milvus#3]
When I successfully start embed Milvus, it will show error:
```python
>>> import milvus
---(For linux users) if you are running Milvus for the first time, run milvus.before() for env variables setting instructions---
---otherwise, run milvus.start()---
>>> milvus.start()
>>> ---Milvus Proxy successfully initialized and ready to serve!---

>>>
>>> from pymilvus import (
...     connections,
...     utility,
...     FieldSchema,
...     CollectionSchema,
...     DataType,
...     Collection,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zilliz_support/.local/lib/python3.6/site-packages/pymilvus/__init__.py", line 13, in <module>
    from .client.stub import Milvus
  File "/home/zilliz_support/.local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 3, in <module>
    from .grpc_handler import GrpcHandler
  File "/home/zilliz_support/.local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 10, in <module>
    from ..grpc_gen import milvus_pb2_grpc
  File "/home/zilliz_support/.local/lib/python3.6/site-packages/pymilvus/grpc_gen/milvus_pb2_grpc.py", line 5, in <module>
    from . import common_pb2 as common__pb2
  File "/home/zilliz_support/.local/lib/python3.6/site-packages/pymilvus/grpc_gen/common_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/zilliz_support/.local/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
AttributeError: module 'google.protobuf.internal.containers' has no attribute 'MutableMapping'
```

**Comment by shiyu22** [comment]
Get it, I have updated python3.6.9 to python3.8 according to that issue and it works, so maybe embed-milvus required python>3.6 instead of python>=3.6.
<img width="991" alt="截屏2022-05-13 12 04 05" src="https://user-images.githubusercontent.com/53459423/168209056-03de5eae-dbee-4d8b-b430-e6bdd0ea2c5c.png">
.

**Comment by soothing-rain** [comment]
> Get it, I have updated python3.6.9 to python3.8 according to that issue and it works, so maybe embed-milvus required python>3.6 instead of python>=3.6. <img alt="截屏2022-05-13 12 04 05" width="991" src="https://user-images.githubusercontent.com/53459423/168209056-03de5eae-dbee-4d8b-b430-e6bdd0ea2c5c.png"> .

Done.

**Comment by shiyu22** [comment]
I think the README has not been updated.

**Comment by soothing-rain** [comment]
resolved.
