### ISSUE TITLE
Start milvus failed

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/embd-milvus#7]
When I finished the preparations, got an error to run `milvus.start()`:
```python
Python 3.8.2 (default, Nov  4 2020, 21:23:28)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import milvus
--- if you are running Milvus for the first time, type milvus.before() for pre-run instructions ---
--- otherwise, type milvus.start() ---
>>> milvus.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chenshiyu/.virtualenvs/shiyu/lib/python3.8/site-packages/milvus/__init__.py", line 56, in start
    library = ctypes.cdll.LoadLibrary(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/chenshiyu/.virtualenvs/shiyu/lib/python3.8/site-packages/milvus/bin/embd-milvus.so, 0x0006): Library not loaded: /Users/binbin/embeded_milvus/milvus/internal/core/output/lib/libmarisa.0.dylib
  Referenced from: /private/var/bin/e-milvus/lib/libmilvus_indexbuilder.dylib
  Reason: tried: '/Users/binbin/embeded_milvus/milvus/internal/core/output/lib/libmarisa.0.dylib' (no such file), '/usr/local/lib/libmarisa.0.dylib' (no such file), '/usr/lib/libmarisa.0.dylib' (no such file)Library not loaded: /Users/binbin/embeded_milvus/milvus/internal/core/output/lib/libmarisa.0.dylib
  Referenced from: /private/var/bin/e-milvus/lib/libmilvus_segcore.dylib
  Reason: tried: '/Users/binbin/embeded_milvus/milvus/internal/core/output/lib/libmarisa.0.dylib' (no such file), '/usr/local/lib/libmarisa.0.dylib' (no such file), '/usr/lib/libmarisa.0.dylib' (no such file)
```

**Comment by huhaibin** [comment]
跟你遇到了一样的问题，不过貌似没人回复呀
![image](https://user-images.githubusercontent.com/22787796/187856338-a4bc96f8-0d2a-46f5-b70f-dec0f19b682d.png)

**Comment by shiyu22** [comment]
> 跟你遇到了一样的问题，不过貌似没人回复呀 ![image](https://user-images.githubusercontent.com/22787796/187856338-a4bc96f8-0d2a-46f5-b70f-dec0f19b682d.png)

Actually, it was solved in my machine(Mac intel) with the newest version, maybe you can try the newest following README.

**Comment by huhaibin** [comment]
> > 跟你遇到了一样的问题，不过貌似没人回复呀 ![image](https://user-images.githubusercontent.com/22787796/187856338-a4bc96f8-0d2a-46f5-b70f-dec0f19b682d.png)
> 
> Actually, it was solved in my machine(Mac intel) with the newest version, maybe you can try the newest following README.

What version of milvus are you using?
I got the error with milvus v2.1.0 in my mac m1.

**Comment by soothing-rain** [comment]
> > > 跟你遇到了一样的问题，不过貌似没人回复呀 ![image](https://user-images.githubusercontent.com/22787796/187856338-a4bc96f8-0d2a-46f5-b70f-dec0f19b682d.png)
> > 
> > 
> > Actually, it was solved in my machine(Mac intel) with the newest version, maybe you can try the newest following README.
> 
> What version of milvus are you using? I got the error with milvus v2.1.0 in my mac m1.

Hey the original issue is resolved but I forgot to close this thread.

Can you double if you `DYLD_FALLBACK_LIBRARY_PATH` value has been set correctly as instructed in `milvus.start()`?

`export DYLD_FALLBACK_LIBRARY_PATH=DYLD_FALLBACK_LIBRARY_PATH:/usr/lib:/usr/local/lib:/var/bin/e-milvus/lib/`

**Comment by soothing-rain** [comment]
> > > 跟你遇到了一样的问题，不过貌似没人回复呀 ![image](https://user-images.githubusercontent.com/22787796/187856338-a4bc96f8-0d2a-46f5-b70f-dec0f19b682d.png)
> > 
> > 
> > Actually, it was solved in my machine(Mac intel) with the newest version, maybe you can try the newest following README.
> 
> What version of milvus are you using? I got the error with milvus v2.1.0 in my mac m1.

Also please be aware that the env variable only works in a single terminal window.

**Comment by soulteary** [comment]
[this pr](https://github.com/milvus-io/embd-milvus/pull/20) will avoid things like this
