### ISSUE TITLE
再插入数据的时候 读取大概率报 can't add empty string into payload一旦报错就再也启动不了

### ISSUE THREAD

**Issue by npctian** [milvus-io/embd-milvus#9]
[2022/08/24 22:01:11.141 +08:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:402] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:can't add empty string into payload\nattempt #2:can't add empty string into payload\nattempt #3:can't add empty string into payload\nattempt #4:can't add empty string into payload\nattempt #5:can't add empty string into payload\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\tD:/a/milvus/milvus/internal/datanode/flow_graph_insert_buffer_node.go:402\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\tD:/a/milvus/milvus/internal/util/flowgraph/node.go:102"]
panic: insertBufferNode flushBufferData failed, err = All attempts results:
attempt #1:can't add empty string into payload
attempt #2:can't add empty string into payload
attempt #3:can't add empty string into payload
attempt #4:can't add empty string into payload
attempt #5:can't add empty string into payload

goroutine 6196 [running]:
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc003835ef0, {0xc0037674b0?, 0x1?, 0x1?})
        D:/a/milvus/milvus/internal/datanode/flow_graph_insert_buffer_node.go:403 +0x3039
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc0018cf800)
        D:/a/milvus/milvus/internal/util/flowgraph/node.go:102 +0x1f3
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
        D:/a/milvus/milvus/internal/util/flowgraph/node.go:70 +0x79

**Comment by npctian** [comment]
现在发现即使没有插入数据的情况下  load() 也大概率会报上面的错误  而且重启无效 必须清空数据才能启动服务。无语这也能用？

**Comment by soothing-rain** [comment]
Hey please refer to: https://github.com/milvus-io/milvus/issues/18872 as this is a known issue to Milvus 2.1
